### PR TITLE
update

### PR DESCRIPTION
**Pull request by hexorer**
write-up for challenges I solved.

### CODE REVIEW

**Comment by LiquidLemon** [comment]
Your solutions aren't writeups. Please provide a written walkthrough of your explanation of how they work. Try to do it in a format similar to the one found in writeups present in this repository.

On another note I'm not sure about including 67 thousand files in a repository. Even when compressed they will at least triple this repository's size. I would consider hosting them somewhere else and providing a download link. These are just my thoughts though.

**Comment by hexorer** [comment]
Okay, we'll be done till Tuesday.

**Comment by ValarDragon** [comment]
I would like to second not putting 67k files in the directory.
Could you compress them all, or just link to the [official source files](https://github.com/EasyCTF/easyctf-2017-problems/blob/master/r3ndom-67k/bins.zip) (From the easyctf team)
Also Lemon is right, what you put here isn't writeups, you just put the solution for doubly dangerous, not an explanation/walkthrough of how you did it.

**Comment by Kage** [comment]
I'm closing this pull request due to age, and that its commit history would be unnecessarily polluting to this project.

Please feel free to open a new pull request with more refined information.

**Pull request closed without merging**
